from __future__ import annotations

import json
import statistics
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

from psycopg import connect
from psycopg.rows import dict_row

from app.config import DATABASE


CREATE_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS raw_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    channel TEXT NOT NULL,
    export_mode TEXT NOT NULL DEFAULT 'aggregated',
    topic TEXT,
    payload_json JSONB NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS sensor_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    channel TEXT NOT NULL,
    export_mode TEXT NOT NULL DEFAULT 'aggregated',
    sensor_name TEXT NOT NULL,
    numeric_value DOUBLE PRECISION,
    text_value TEXT,
    unit TEXT,
    recorded_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sensor_readings_recorded_at
ON sensor_readings(recorded_at);

CREATE INDEX IF NOT EXISTS idx_sensor_readings_sensor_name
ON sensor_readings(sensor_name);

CREATE INDEX IF NOT EXISTS idx_raw_messages_recorded_at
ON raw_messages(recorded_at);

CREATE OR REPLACE VIEW latest_sensor_values AS
SELECT DISTINCT ON (source, channel, export_mode, sensor_name)
    source,
    channel,
    export_mode,
    sensor_name,
    numeric_value,
    text_value,
    unit,
    recorded_at
FROM sensor_readings
ORDER BY source, channel, export_mode, sensor_name, recorded_at DESC;

CREATE OR REPLACE VIEW sensor_series_numeric AS
SELECT
    source,
    channel,
    export_mode,
    sensor_name,
    numeric_value,
    unit,
    recorded_at,
    date_trunc('hour', recorded_at) AS recorded_hour,
    date_trunc('day', recorded_at) AS recorded_day
FROM sensor_readings
WHERE numeric_value IS NOT NULL;

CREATE OR REPLACE VIEW hourly_sensor_stats AS
SELECT
    source,
    channel,
    export_mode,
    sensor_name,
    unit,
    date_trunc('hour', recorded_at) AS recorded_hour,
    COUNT(*) AS samples,
    ROUND(AVG(numeric_value)::numeric, 3) AS avg_value,
    ROUND(MIN(numeric_value)::numeric, 3) AS min_value,
    ROUND(MAX(numeric_value)::numeric, 3) AS max_value,
    ROUND(COALESCE(STDDEV_POP(numeric_value), 0)::numeric, 3) AS stddev_value,
    MAX(recorded_at) AS last_seen
FROM sensor_readings
WHERE numeric_value IS NOT NULL
GROUP BY
    source,
    channel,
    export_mode,
    sensor_name,
    unit,
    date_trunc('hour', recorded_at);
"""


def _schema_statements() -> List[str]:
    return [statement.strip() for statement in CREATE_SCHEMA_SQL.split(";") if statement.strip()]


def _connection_dsn() -> str:
    return (
        "host={host} "
        "port={port} "
        "dbname={dbname} "
        "user={user} "
        "password={password}"
    ).format(
        host=DATABASE["host"],
        port=DATABASE["port"],
        dbname=DATABASE["name"],
        user=DATABASE["user"],
        password=DATABASE["password"],
    )


def _connect_sync():
    return connect(_connection_dsn(), row_factory=dict_row)


def _guess_unit(sensor_name: str) -> Optional[str]:
    suffix_to_unit = {
        "_temperature_c": "C",
        "_pressure_hpa": "hPa",
        "_humidity_pct": "%",
        "_relative_pct": "%",
        "_speed_kmh": "km/h",
        "_gas_kohms": "kOhms",
        "_rain_mm": "mm",
        "_rain_mm_total": "mm",
        "_dir_deg": "deg",
    }
    for suffix, unit in suffix_to_unit.items():
        if sensor_name.endswith(suffix):
            return unit
    return None


def _normalize_payload(payload: Dict[str, Any]) -> List[Tuple[str, Optional[float], Optional[str], Optional[str]]]:
    readings = []
    for key, value in payload.items():
        if key in {"timestamp", "export_mode"}:
            continue
        if key.startswith("error_"):
            readings.append((key, None, str(value), None))
            continue
        if isinstance(value, bool):
            readings.append((key, float(value), None, None))
            continue
        if isinstance(value, (int, float)):
            readings.append((key, float(value), None, _guess_unit(key)))
            continue
        if isinstance(value, str):
            readings.append((key, None, value, _guess_unit(key)))
    return readings


def _to_isoformat(value: Any) -> Any:
    if isinstance(value, datetime):
        return value.isoformat()
    return value


def _normalize_row(row: Dict[str, Any]) -> Dict[str, Any]:
    normalized = dict(row)
    if "recorded_at" in normalized:
        normalized["recorded_at"] = _to_isoformat(normalized["recorded_at"])
    if "payload_json" in normalized and not isinstance(normalized["payload_json"], str):
        normalized["payload_json"] = json.dumps(normalized["payload_json"])
    return normalized


def init_db() -> None:
    if not DATABASE.get("enabled", True):
        return
    with _connect_sync() as connection:
        with connection.cursor() as cursor:
            for statement in _schema_statements():
                cursor.execute(statement)
        connection.commit()


def store_payload(source: str, channel: str, topic: Optional[str], payload: Dict[str, Any], recorded_at: str) -> None:
    if not DATABASE.get("enabled", True):
        return

    store_raw_messages = DATABASE.get("store_raw_messages", True)
    store_sensor_readings = DATABASE.get("store_sensor_readings", True)
    if not store_raw_messages and not store_sensor_readings:
        return

    rows = _normalize_payload(payload)
    export_mode = str(payload.get("export_mode") or ("raw" if topic and topic.endswith("/raw") else "aggregated"))
    with _connect_sync() as connection:
        with connection.cursor() as cursor:
            if store_raw_messages:
                cursor.execute(
                    """
                    INSERT INTO raw_messages(source, channel, export_mode, topic, payload_json, recorded_at)
                    VALUES (%s, %s, %s, %s, %s::jsonb, %s::timestamptz)
                    """,
                    (source, channel, export_mode, topic, json.dumps(payload), recorded_at),
                )
            if store_sensor_readings and rows:
                cursor.executemany(
                    """
                    INSERT INTO sensor_readings(
                        source, channel, export_mode, sensor_name, numeric_value, text_value, unit, recorded_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s::timestamptz)
                    """,
                    [
                        (source, channel, export_mode, sensor_name, numeric_value, text_value, unit, recorded_at)
                        for sensor_name, numeric_value, text_value, unit in rows
                    ],
                )
        connection.commit()


def fetch_latest_readings(limit: int = 25, export_mode: Optional[str] = None) -> List[Dict[str, Any]]:
    query = """
    SELECT source, channel, export_mode, sensor_name, numeric_value, text_value, unit, recorded_at
    FROM sensor_readings
    {where_clause}
    ORDER BY recorded_at DESC
    LIMIT %s
    """
    where_clause = ""
    params: Tuple[Any, ...] = (limit,)
    if export_mode:
        where_clause = "WHERE export_mode = %s"
        params = (export_mode, limit)
    with _connect_sync() as connection:
        with connection.cursor() as cursor:
            cursor.execute(query.format(where_clause=where_clause), params)
            rows = cursor.fetchall()
    return [_normalize_row(row) for row in rows]


def fetch_latest_messages(limit: int = 20, export_mode: Optional[str] = None) -> List[Dict[str, Any]]:
    query = """
    SELECT source, channel, export_mode, topic, payload_json, recorded_at
    FROM raw_messages
    {where_clause}
    ORDER BY recorded_at DESC
    LIMIT %s
    """
    where_clause = ""
    params: Tuple[Any, ...] = (limit,)
    if export_mode:
        where_clause = "WHERE export_mode = %s"
        params = (export_mode, limit)
    with _connect_sync() as connection:
        with connection.cursor() as cursor:
            cursor.execute(query.format(where_clause=where_clause), params)
            rows = cursor.fetchall()
    return [_normalize_row(row) for row in rows]


def fetch_reduced_stats(export_mode: Optional[str] = "aggregated") -> List[Dict[str, Any]]:
    query = """
    SELECT sensor_name, unit, numeric_value, recorded_at
    FROM sensor_readings
    WHERE numeric_value IS NOT NULL
    {mode_clause}
    ORDER BY sensor_name, recorded_at
    """
    mode_clause = ""
    params: Tuple[Any, ...] = ()
    if export_mode:
        mode_clause = "AND export_mode = %s"
        params = (export_mode,)
    with _connect_sync() as connection:
        with connection.cursor() as cursor:
            cursor.execute(query.format(mode_clause=mode_clause), params)
            rows = cursor.fetchall()

    grouped: Dict[Tuple[str, str], List[Dict[str, Any]]] = {}
    for row in rows:
        key = (row["sensor_name"], row["unit"] or "")
        grouped.setdefault(key, []).append(row)

    stats: List[Dict[str, Any]] = []
    for (sensor_name, unit), group_rows in grouped.items():
        values = [float(row["numeric_value"]) for row in group_rows]
        avg_value = round(statistics.mean(values), 3)
        median_value = round(statistics.median(values), 3)
        stddev_value = round(statistics.pstdev(values), 3) if len(values) > 1 else 0.0
        min_value = round(min(values), 3)
        max_value = round(max(values), 3)
        stats.append(
            {
                "sensor_name": sensor_name,
                "unit": unit,
                "samples": len(values),
                "avg_value": avg_value,
                "mean_value": avg_value,
                "median_value": median_value,
                "stddev_value": stddev_value,
                "min_value": min_value,
                "max_value": max_value,
                "last_seen": _to_isoformat(group_rows[-1]["recorded_at"]),
            }
        )

    stats.sort(key=lambda item: item["sensor_name"])
    return stats
